#Text Data
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton,CallbackQuery

gen_btns=InlineKeyboardMarkup([[
            InlineKeyboardButton("Pyrogram", callback_data="pyrogram"),
            InlineKeyboardButton("Telethon", callback_data="telethon")
        ]])

start_btns=InlineKeyboardMarkup([[
            InlineKeyboardButton("Generate Session 🔥", callback_data="generate"),
        ]])

log_channel=-1001283100768

start_text="""👋🏻 Hi {},

<b>I'm String Session Generator 
I Can Generate Session String of 
Both Library's Pyrogram and Telethon.
</b>
Press /generate command and i will start my work.

Get API_ID from https://my.telegram.org"""

Send_Num='Now please send your `PHONE_NUMBER` along with the country code. \nExample : `+19876543210`'

Val_Err='Not a valid API_ID (which must be an integer). Please start generating session again.'

Api_id_Err='`API_ID` and `API_HASH` combination is invalid. Please start generating session again.'

Phone_Err='`PHONE_NUMBER` is invalid. Please start generating session again.'

check_otp="Please check for an OTP in Telegram app . \n\nIf you got it, send OTP here after reading the below format. \nIf OTP is `12345`, **please send it as** `1 2 3 4 5`."

Time_Out='Time limit reached of 10 minutes. Please start generating session again.'

Otp_Err='OTP is invalid. Please start generating session again.'

Two_step='Your account has enabled two-step verification. Please provide the password.'

Invalid_Pass='Invalid Password Provided. Please start generating session again.'


Otp_Expir='OTP is expired. Please start generating session again.'

Suc_text="**Successfully generated {} string session. **\n\nPlease check your saved messages! \n\nBy @CrazeBots "

save_msg="**{} STRING SESSION** \n\n`{}` \n\n**Generated by {}**"
